# Generated by Django 5.2.8 on 2025-11-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contect',
            old_name='Contect',
            new_name='Content',
        ),
    ]
